// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI38egdXV4QXUDfmnOs9ijkBbgsDF8dMw',
    appId: '1:119833330228:web:e931ff0bdc147980960061',
    messagingSenderId: '119833330228',
    projectId: 'chatapp-c1b1f',
    authDomain: 'chatapp-c1b1f.firebaseapp.com',
    storageBucket: 'chatapp-c1b1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjjsVK7yTXNUXSDRm-aDF-Ugfkci8bMHI',
    appId: '1:119833330228:android:b50caf142e2d840a960061',
    messagingSenderId: '119833330228',
    projectId: 'chatapp-c1b1f',
    storageBucket: 'chatapp-c1b1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC194Lhl9_7_4cLeTFlT1ShWEcUHHHTSnc',
    appId: '1:119833330228:ios:29f80f7b469b3f3b960061',
    messagingSenderId: '119833330228',
    projectId: 'chatapp-c1b1f',
    storageBucket: 'chatapp-c1b1f.appspot.com',
    iosBundleId: 'com.example.sample2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC194Lhl9_7_4cLeTFlT1ShWEcUHHHTSnc',
    appId: '1:119833330228:ios:29f80f7b469b3f3b960061',
    messagingSenderId: '119833330228',
    projectId: 'chatapp-c1b1f',
    storageBucket: 'chatapp-c1b1f.appspot.com',
    iosBundleId: 'com.example.sample2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI38egdXV4QXUDfmnOs9ijkBbgsDF8dMw',
    appId: '1:119833330228:web:44e3841af9c46a28960061',
    messagingSenderId: '119833330228',
    projectId: 'chatapp-c1b1f',
    authDomain: 'chatapp-c1b1f.firebaseapp.com',
    storageBucket: 'chatapp-c1b1f.appspot.com',
  );

}